### ISSUE TITLE
Android 4.0 Support

### ISSUE THREAD

**Issue by jakehaas** [shusain93/Andromeda-iMessage#23]
Hello,

 I am wondering if there is any possible way to add Android 4.0 support.

I recently found my old Atrix 2 and wanted to use it with my Lapdock, but it's max OS version is 4.0.4

**Comment by ezhes** [comment]
I mean maybe, you could try lower the build version but I’m going to guess it’s not going to work since the UI uses lollipop elements. I’ve only gotten it down to KitKat. 

In all honesty if your Android device is that old I’d be worried about using it on the open internet since there are so many known vulnerabilities
