### ISSUE TITLE
Great Project

### ISSUE THREAD

**Issue by jimmyle1511** [shusain93/Andromeda-iMessage#6]
This is a great project. I wonder why apple and google haven't figure this out yet, or they just want to keep it seperate because of the private api.

Anyway, everything work perfect. I got a crash on open client when the port is empty, i thought the port is default if leave empty but if the field left empty then it will crash when you write the config.

Everything work, picture work as well but can you able turn off read and send from our end so other dont see that you read the message ?

Also, i cant able to connect to the domain as it wont resolve the domain, the domain is publish (tested and confirmed) from other network, also ports are publish as well (tested)
Get error (The server didnt respond com.android.volley.NoconnectionError....UnknowHostException...Unable resolve host "abc.com" No address associated with hostname.

Do you have any timeframe for the picture to be send from the client app ?

Also, i thought, can this server port to written in node js so you can run on NAS server ? without Mac Server ?

**Comment by ezhes** [comment]
Crashing with the default port: known issue, it's currently on the source release so if you build from source you'll have it.

Read recipients: this uses the config on the OSX machine, read receipts would only get sent went you send a message back (or instantly, depending on if the messages app stays inside the conversation). status: won't-fix

Pictures: eta eventually, never ever going to give anyone an eta ever on anything. If you want an eta, I'd probably guess last weekend but really my margin of error is +- never.

DNS errors: not my end, are you sure you're spelling it exactly? Is this internal DNS? Andromeda uses the internal system resolver so can't help there.

Node.js: this project is never leaving OSX because anything else is just begging Apple to sue the pants off ya.
