### ISSUE TITLE
video demonstration 

### ISSUE THREAD

**Issue by aspranav** [shusain93/Andromeda-iMessage#9]
can you please upload a video on YouTube showing how to download it on your android phone 
i'll like, subscribe, share etc...

**Comment by ezhes** [comment]
Sorry, I don't want to make this too easy otherwise I'll be stuck providing tech support for the next century. If you can't follow the setup instructions this build isn't appropriate for you.

I'll keep this open for the time being because I intend to make a promo video but it's not going to be an instructional setup video.

**Comment by aspranav** [comment]
im not a coding person so do you need a computer to do this??

**Comment by ezhes** [comment]
LOL you need a mac to act as a server please read the directions for both the android app project and the server project

**Comment by aspranav** [comment]
I don't even have a mac lool 😭😭😭

_Sent from my LGE LG-H812 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by aspranav** [comment]
I'm willing to pay if you do this for me 

_Sent from my LGE LG-H812 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ezhes** [comment]
If I make any money off this I'll get my ass sued off by Apple. There is a very specific reason why this is all FOSS. 

And anyways - I'd have to keep a mac server running just for you and that wouldn't be cheap. Maybe try asking around in your friend group? Really can't help you. You'll probably be disappointed because this isn't entirely perfect or complete because while it's functional enough to be useful on a daily basis you still can't do seemingly basic things like send photos

**Comment by aspranav** [comment]
oh well 
thanks anyway
